application: twitlist
version: 1
runtime: go
api_version: go1

handlers:
- url: /lists/.*
  script: _go_app
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /
  static_dir: static
